### ISSUE TITLE
Attributes summary rendering problem with the Astropy autosummary customizations

### ISSUE THREAD

**Issue by josePhoenix** [astropy/astropy-helpers#116]
When building the POPPY docs, which use the Astropy helpers, I noticed a weird rendering problem with the class attributes summary that I believe is due to customizations in the helpers.

![astropy_autosummary_enabled](https://cloud.githubusercontent.com/assets/172886/5479720/ea989df6-860d-11e4-8ec8-8d81b7249b8b.png)

To diagnose it, I edited `astropy_helpers/sphinx/ext/astropyautosummary.py` to change the name of `get_items` to `bogus_get_items` (making it functionally identical to Sphinx's built-in autosummary). This makes the output look like I expect it to.

![astropy_autosummary_disabled](https://cloud.githubusercontent.com/assets/172886/5479722/f268ddac-860d-11e4-947d-5532fdef767b.png)

@embray suggested I submit an issue (and ping @eteq )

**Comment by embray** [comment]
Good that it has a workaround.  I'm going to go ahead and try my proposal of basically deprecating `AstropyAutosummary` and disabling it where it isn't needed.

**Comment by embray** [comment]
Just to be clear (I wanted to make absolutely sure about this before I made any changes) it does appear that this broke with Sphinx 1.2, and that it worked with Sphinx 1.1 (though other things don't and in fact Astropy sets Sphinx 1.2.1 as a minimum for building its docs).  So I think `AstropyAutosummary` can be deprecated, and dropped soon after.

**Comment by josePhoenix** [comment]
I just ran the docs build with that workaround and it didn't fully resolve the issue. If you're around tomorrow, could you have a look? I can provide more detailed info when in front of my computer.

**Comment by embray** [comment]
You mean, `extensions.remove('astropy_helpers.sphinx.ext.astropyautosummary')` didn't fix it after all?

**Comment by embray** [comment]
If so, I think I might see the problem.  It looks like `astropy_helpers.sphinx.ext.automodsumm` also loads `astropyautosummary` anyways:

https://github.com/astropy/astropy-helpers/blob/master/astropy_helpers/sphinx/ext/automodsumm.py#L573

This makes sense since automodsumm generates module autosummary sections.  I'll try my recommended patch to astropyautosummary to just be a thin wrapper around Sphinx's built-in autosummary for newer versions of Sphinx.

**Comment by embray** [comment]
Okay, I tried setting `AstropyAutosummary` to be deprecated, and automodsumm does not use it in Sphinx 1.2.  This seems to mostly work.  A spot check of a number of documentation pages seems to look fine, and it doesn't seem to introduce any regressions on most past issues with autosummary or automodsumm.

Just a couple issues:
1. After making this change I get a mysterious
```
<autodoc>:0: WARNING: Literal block expected; none found.
```
in the build log, which is definitely a problem.  No idea where it's coming from.  But it should be tracked down...
2. The "Attributes Summary" for [this page](http://docs.astropy.org/en/latest/api/astropy.modeling.Model.html#model) (which I use kind of as my acid test) does no show documentation for the `name` property even though it has a docstring.  This property was broken before this change too, but now it's broken in a new way that I'll have to track down.

**Comment by josePhoenix** [comment]
It's possible I'm seeing a different but related issue. In our case, poppy/__init__.py imports Wavefront from poppy_core.py and other things like CircularAperture from optics.py. The classes are made available as poppy.Wavefront and poppy.CircularAperture. In the docs, referencing them by the "user friendly" name rather than the fully qualified one works for Wavefront and not for CircularAperture.

**Comment by embray** [comment]
Hmm.  The first issue is caused by a docstring for `astropy.utils.xml.writer.XMLWriter.tag` which begins `u'A convenience method for use with the ``with`` statement::'`, and it's taking that as the summary to use in the autosummary table.  The fact that it ends with `::` is where the warning comes up.  Presumably our version of autosummary fixes this, but I don't see why or how.  @eteq might know more.

**Comment by embray** [comment]
@josePhoenix I don't think that's a particularly related issue.  See astropy/astropy#1826, though I admit I don't understand the intricacies of that.

**Comment by embray** [comment]
It looks like in the [current docs](http://docs.astropy.org/en/stable/api/astropy.utils.xml.writer.XMLWriter.html#astropy.utils.xml.writer.XMLWriter) the tag method in question has its summary displayed as:

```
A convenience method for use with the with statement:: with writer.tag(‘foo’): writer.element(‘bar’) # </foo> is implicitly closed here Parameters are the same as to start.
```

so it's smushing the example code in there as well.  What I might do for now is just rewrite that docstring, and worry about a workaround in autosummary later....

**Comment by josePhoenix** [comment]
Oh, whoops, I was replying from my phone and thought this was a different issue. My mistake!

**Comment by embray** [comment]
As to my second issue, the `Model.name` property, it seems that autodoc does not propertly handle (the admitted rare, but not unheard of) case where a class attribute is also a property on the class's metaclass.  In the case of `Model` there *is* a a `name` property defined in the `Model` class, but there is also a `name` property defiend in the `_ModelMeta` metaclass.  `getattr(Model, 'name')` ends up evaluating the `name` property on the metaclass and returning a string, instead of just returning the `property` *object* for name.  Going to have to give that one a bit more thought, since this might affect a few other things in the modeling package.  But it's probably mostly only limited to that package....

**Comment by josePhoenix** [comment]
This appears to have been fixed at some point between 2014 and now
