### ISSUE TITLE
Catch KeyboardInterrupt and pass to pytest during test run

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy-helpers#134]
If you run a test session using the pytest CLI and you hit an import error or similar you can interrupt the test run and see the error traceback without having to wait for the whole test run to complete. Would it be possible to replicate this behaviour inside setup.py?

**Comment by embray** [comment]
Incidentally I believe this is *not* an issue for astropy-helpers, as the astropy test runner lives in astropy itself.

I've noticed the same thing before.  Sometimes a Ctrl+C interrupt works for me, and sometimes it doesn't.  It must have to do with the tests being run in the subprocess, and for some reason the subprocess is not obeying the interrupt.

**Comment by Cadair** [comment]
I wondered if it was something in the setuptools hook not passing the interrupt to the subprocess, so that makes some sense.

**Comment by embray** [comment]
Not exactly--the Astropy test runner that wraps py.test has nothing specifically to do with setuptools.  It gets invoked when you run `astropy.test()` as well.

**Comment by Cadair** [comment]
I will open this on the astropy side, and try and experiment on the magical 8th day in this week ;)

**Comment by embray** [comment]
As mentioned in astropy/astropy#3460 I was wrong--it's only in the `./setup.py test` command provided by astropy-helpers that a subprocess is used.  Which is *probably* the cause of this issue.  Though it's still odd that this would happen since the subprocess should still belong to the same process group and handle the SIGINT.  I also wonder if it has something to do with the py.test version?

**Comment by embray** [comment]
Despite my last comment, this would now be problem solely on the astropy side.
