### ISSUE TITLE
Code links have turned grey

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-helpers#163]
In the latest version of the Astropy and affiliated package docs, code and API links have now turned grey!

![screen shot 2015-05-07 at 11 37 57 pm](https://cloud.githubusercontent.com/assets/314716/7526476/2566b206-f512-11e4-83c9-d77f74f3647f.png)

![screen shot 2015-05-07 at 11 38 06 pm](https://cloud.githubusercontent.com/assets/314716/7526475/2564c7f2-f512-11e4-870e-fec2eba2c0c7.png)

@mdboom: you adjusted the CSS recently, could it be due to that?

**Comment by mdboom** [comment]
Seems extremely unlikely that it's due to 4af05096016f0301ef4d4137c94ecd566589fd47.

It looks like it's due to moving to Sphinx 1.3 (maybe readthedocs recently updated)?  The relevant change is this:

https://bitbucket.org/birkenfeld/sphinx/pull-request/269/fix-1476-replace-tag-by/diff

All the <tt> tags were replaced with <code>, as apparently <tt> is deprecated.  We'll need to update our CSS accordingly.

**Comment by embray** [comment]
I noted that as an issue when I first got the docs building with Sphinx 1.3.  The issue doesn't happen on Sphinx 1.2 and I didn't have a chance to investigate.
