### ISSUE TITLE
pip install astropy-helpers does not install sphinx

### ISSUE THREAD

**Issue by danielsf** [astropy/astropy-helpers#201]
This makes it difficult to incorporate astropy-helpers into other automatically built packages if the build systems try to create the documents (which rely on sphinx).

We are currently running into this problem trying to incorporate astropy-helpers into a conda-installed version of the LSST simulations software stack.

**Comment by danielsf** [comment]
It also looks like the package needs to install pytest in order to successfully run

**Comment by embray** [comment]
Could you maybe go into more details of what it is you're trying to do?  This is deliberate, in part because Sphinx is only an optional dependency and only used in doc builds, whereas astropy-helpers has other functionality as a build/installation tool.  (One could make a valid argument that its dual purpose is a problem and it should be further split into more packages, but this is a logistical hassle).

**Comment by danielsf** [comment]
We are writing scripts to automatically generate and package a conda build of software that depends on astropy-helpers.  The bug we ran into is that, just including astropy-helpers in our meta.yaml recipes fails because, when conda calls pip to install astropy-helpers, it automatically tries to run the unit tests and build the documentation.  It cannot do this without sphinx or pytest, and 'pip install astropy' did not install either package.  We got around this by adding sphinx and pytest to our recipes by hand.

So: we have worked around this issue and it is no longer a problem for our specific use case.  I can see how this might not be big enough to try to fix.

**Comment by embray** [comment]
That's weird about conda.  The problem is there's not really a great way, currently, to specify test dependencies in a Python package as opposed to strict runtime dependencies, though that is part of the long-term work of overhauling Python packaging.  But adding these to `install_requires` for astropy-helpers would be a problem.  Technically astropy-helpers isn't even supposed to be "installed" as such, except when used as a dependency for doc builds.  So I'm a little concerned about that.

What package is listing astropy-helpers as a dependency?

**Comment by danielsf** [comment]
sncosmo

https://github.com/sncosmo/sncosmo

**Comment by embray** [comment]
sncosmo uses astropy-helpers as a build dependency and for a docs dependency, but it does not (nor should it) use it as a runtime dependency.  So a package for it shouldn't be installing astropy-helpers as though it were a depedency.

**Comment by danielsf** [comment]
all I know is that when we tried to build sncosmo, conda complained that it did not have astropy-helpers installed
