### ISSUE TITLE
ez_setup is deprecated

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-helpers#297]
Current version of ez_setup.py comes with a big deprecation at the top, so we should also revise its usage here ideally by the 2.0 release.

**Comment by astrofrog** [comment]
Have they suggested a replacement?

**Comment by bsipocz** [comment]
It seems that pip installing, but I haven't looked into the very details yet. Our build against the dev version is hopelessly broken though, but it may be an issue upstream as I couldn't hack it last night.

The last ez_setup version is for setuptools 33.1.1, which is fairly recent, so as a workaround we could stick with that for a while (conda still ships v27.x).

**Comment by saimn** [comment]
Interesting, so from I can read:
- They dropped self-upgrade support in setuptools (https://github.com/pypa/setuptools/issues/581)
- With [PEP-518](https://www.python.org/dev/peps/pep-0518/) it is (will be ?) possible to tell pip the required build dependencies, with a `pyproject.toml` file. 
- So I guess the idea to replace `ez_setup` is simply to tell pip that (a recent) setuptools is required. But I don't see what should be done for users with an old pip, other than telling them to upgrade pip ?
- An interesting related point is that it is now possible to configure `setup()` using `setup.cfg` files, in a way similar to what astropy_helpers/package_template do (or pbr, d2to1): https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files . If it become easy to require a recent version of setuptools, this looks great.

**Comment by embray** [comment]
I noticed that last bullet point recently as well and thought of bringing it up here.  The problem is, as you say, it requires a recent version of setuptools.  What one might be able to do is move that functionality to astropy-helpers (if it hasn't been already) and just enable it when needed for backwards-compatibility.  Then most package maintainers will almost never have to touch setup.py itself which is a good thing.

**Comment by bsipocz** [comment]
For 2.0.0 we plan to ship with latest ``ez_setup.py``, but will get rid of it in 3.0.0

**Comment by astrofrog** [comment]
I think the path forward for ``ez_setup.py`` is that we should remove it, and also update the astropy installation docs so that users installing locally should use ``pip install .`` rather than ``python setup.py install``. Recent versions of pip should install setuptools automatically, but for older versions I think most users will anyway have setuptools installed in their environments, so I think this isn't a big deal.

**Comment by astrofrog** [comment]
Thinking about this again - we should maybe keep ``ez_setup.py`` for the foreseeable future. It turns out that if you want to run e.g. ``python setup.py test`` or ``python setup.py build_docs`` then you still need ``ez_setup.py`` to make sure setuptools is installed. I asked the setuptools folks and they said that the idea is that people should actually not use setup.py commands anymore in the long term: https://github.com/pypa/setuptools/issues/1156 - of course a short term solution is to simply require setuptools to be installed before running ``setup.py``, but in that case we should make it explicit in the docs. This wouldn't be a problem for anyone installing astropy with conda or pip, but would be for anyone running commands in the repo (so mostly developers).

So the options for now are either keep the ``ez_setup.py`` file or require ``setuptools`` for people who want to use ``setup.py`` in some way.

**Comment by astrofrog** [comment]
Huh apparently pip will provide an sdist command (https://github.com/pypa/setuptools/issues/1156). Anyway, all these things are not short term, so the only short term decision to make is whether we remove ``ez_setup.py`` and require setuptools.

**Comment by saimn** [comment]
It seems safe to require setuptools, it is installed probably almost everywhere (conda and virtualenv have it by default I think) and required by many packages. On my other projects I just use setuptools directly and never got complaints about this.

**Comment by bsipocz** [comment]
Let's delay it one more time...

**Comment by astrofrog** [comment]
Removed in #384 for reasons outlined there.
