### ISSUE TITLE
Try to loosen the install-time sphinx dependencies

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-helpers#320]
@josePhoenix  reported a problem in #319 that can be traced back to sphinx doing an update that broke some of the astropy sphinx machinery in a way that made even a non-doc build fail.  While that *specific* issue has been resolved in the current helpers, it begs a question: can we "protect" the sphinx imports better in some way so that if they fail the exceptions don't kill the whole build process?

Right now if sphinx isn't installed this is caught, but a *failing* sphinx apparently is not.  So perhaps we can  add some `try`/`except` blocks in clever places to convert exceptions into warnings *if* we're not in a ``build_docs`` comamnd?  I'm not sure exactly how much work that will be, but I'm raising it now in the hopes that I or someone else can get to it later.

**Comment by pllim** [comment]
For the particular problem that raised this issue, Sphinx was installed (if it wasn't, the error would not have occurred) but was the incompatible 1.6 version *and* `astropy-helpers` submodule was already fixed by whatever Astropy that was also installed. There is nothing we can do there.

As for future-proofing, we can never predict what is going to change in Sphinx... In this case, the usual `try ... except ...` would be:
```python
try:
    from sphinx.setup_command import BuildDoc as SphinxBuildDoc
except ImportError:
    do_magic
```
but that would not have caught `RecursionError` (and who would think of catching that in an import statement?).

This is tricky. :thinking:

**Comment by josePhoenix** [comment]
I use other packages that depend on Sphinx, and none of those builds broke. So, the question is, what are they doing differently?

A related question would be, how do the astropy helpers cause RecursionErrors in 3rd party packages?

**Comment by pllim** [comment]
`astropy-helpers` add `build_docs` setup command to `setup.py`, so you don't see the error in other packages because they are not as fancy? (Just speculating since I don't know what other packages you are referring to.)

"How" and "why" are good questions... They are why we still have jobs. :sweat_smile:

**Comment by saimn** [comment]
There is already a try/except that skip registering the `build_docs` command if Sphinx is not installed:
https://github.com/astropy/astropy-helpers/blob/master/astropy_helpers/setup_helpers.py#L141

But the recent issue was triggered with Sphinx installed but the import failing in a non-obvious way. It would be easy to catch any exception, and it would avoid breaking the setup.py for users, but it would also hide a bit the issue for developers.

**Comment by bsipocz** [comment]
What it's worth, I'll plan to add a test into our matrix against the sphinx dev version, as this wasn't the first time they messed up our system. That will at least help us see the issues early and report it back to sphinx.

**Comment by astrofrog** [comment]
I'm going to close this, since while this is a 'would be nice', we haven't run into this specific problem much since the issue was opened, and with the transition away from astropy-helpers (APE 17) we won't need to worry about this anymore since Sphinx will just be run directly or via tox.
