### ISSUE TITLE
Packages installed during python setup.py test are not picked up during testing

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-helpers#336]
If ``install_requires`` contains a package, e.g. ``pandas``, then when running:

```
python setup.py test
```

pandas gets downloaded and installed into ``.eggs`` inside the package directory, but this is then ignored when the tests are actually run because I think we change directory to run the tests.

**Comment by pllim** [comment]
I am not familiar with how `setup` works but I wonder if `tests_require` behaves the same way...

**Comment by drdavella** [comment]
@astrofrog, @pllim in astropy core, the reason `tests_require` can't be used is because the tests run in a subprocess, and the downloaded requirements are only made available in the path of the parent process (which is not inherited by the subprocess). I'm not sure whether this is the same issue, though.

**Comment by astrofrog** [comment]
This was fixed in https://github.com/astropy/astropy/pull/6892
