### ISSUE TITLE
Make  it clearer/more discoverable how to use "--no-git"/"--offline"

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-helpers#60]
While trying to do some astropy-helpers development, I noticed an oddity: Doing `python setup.py --offline <whatever>` does _not_ stop astropy_helpers from getting updated from git.  I think that's a bit counter-intuitive.  I would have thought "offline" would mean don't get updates for a release _and_ don't update git (after all, switching to the appropriate commit might require being online, right?).  So is there any reason to not have the `--offline` option also imply `--no-git`?  That is, it would then just act as a "use whatever I have in astropy_helpers right now, don't muck around with it."

An alternative is to introduce a third command that implies the two together.

Note that #31 may sort of "implicitly" resolve this by providing better docs, but it might be clearer to just do this anyway.

cc @embray

**Comment by embray** [comment]
Did anything ever happen with this?  Did I do anything?  I never saw any more followup about it in the issue, and I barely remember what this issue even was except there seems to be a loooong discussion about it.

**Comment by eteq** [comment]
@embray -- I don't think so.  I just tried this now and ``python setup.py <something> --offline`` yields ``git submodule update --no-fetch -- astropy_helpers`` instead of ``git submodule update --rebase --no-fetch -- astropy_helper``, which is what I think the final solution you were planning to implement was.  (Not clear to me now if that's only for ``--offline``, though...)

**Comment by embray** [comment]
Apparently I did that in #67 and mentioned it as "partially" addressing the issue.

**Comment by eteq** [comment]
@embray ? It doesn't look like that changes the update to "git submodule update --rebase", which is the key element of the above.

**Comment by embray** [comment]
Ah...okay.  I'm playing around with `git submodule update --rebase`, and I think there's a danger to this.  If I switch from master to a release branch like:

```
$ git checkout v1.0.x
M	astropy_helpers
Switched to branch 'v1.0.x'
Your branch is up-to-date with 'upstream/v1.0.x'.
[embray@elregulus:astropy]$ git st
On branch v1.0.x
Your branch is up-to-date with 'upstream/v1.0.x'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   astropy_helpers (new commits)

no changes added to commit (use "git add" and/or "git commit -a")
```

It now shows that astropy_helpers is "modified" because it's still at the commit it was on in master.  That commit is off a totally different release branch of astropy-helpers from what it should be on in astropy v1.0.x.

If the default behavior of ah_bootstrap were to run `git submodule update --rebase -- astropy_helpers` you would get a mess like this:

```
$ git submodule update --rebase -- astropy_helpers
First, rewinding head to replay your work on top of it...
Applying: Finishing v1.0 release
Using index info to reconstruct a base tree...
M	CHANGES.rst
M	setup.py
Falling back to patching base and 3-way merge...
Auto-merging setup.py
CONFLICT (content): Merge conflict in setup.py
Auto-merging CHANGES.rst
CONFLICT (content): Merge conflict in CHANGES.rst
Failed to merge in the changes.
Patch failed at 0001 Finishing v1.0 release
The copy of the patch that failed is found in:
   /internal/1/root/home/embray/src/astropy/astropy/.git/modules/astropy_helpers/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

Unable to rebase '160b48587680e11f12b66a51641a2601b869d1fa' in submodule path 'astropy_helpers'
```

Effectively what happened here is it tried to run:

```
$ (cd astropy_helpers && git rebase v1.0.x)
```

In other words it tries to rebase astropy_helpers's master (more or less--whatever commit astropy master has it on) on top of something closer to astropy_helpers v1.0.x.  This is bad enough for us--imagine how this looks to someone who don't quite grasp git rebase.

I think the current behavior is the path of least resistance for the average user switching between development branches of astropy or a related project.  Very few people ever need to touch astropy-helpers directly, much less via the submodule.  *I* don't even do it that often.  When I do want to test astropy with some new commits on astropy-helpers I use the `--no-git` option.  This should be better documented somewhere.

Another thing I do to mitigate problems with this is that I update the `git co` alias in my `.gitconfig` like:

```
$ cat ~/.gitconfig | grep '\[alias\]\|co ='
[alias]
    co = !git checkout $* && git submodule update && :
```

This doesn't help if you're not conditioned to always type "git co" instead of "git checkout" like I am by this point.  But it might be worth putting this in the developer docs...I find it very handy.

**Comment by eteq** [comment]
@embray - I  prefer to modify the helpers inside astropy (or an affiliated package), either to test a modification or just to figure out now something works.  I do indeed use the ``--no-git`` option for that right now... But in my experience most people who don't talk to one of us don't know about that and are really confused when they try to do something with the helpers (to the point of giving up in confusion).

That said, I do see your point that the `rebase` change would be problematic for the case of the user who really does *not* want to fiddle with the helpers.  So you're right that the ``--rebase`` solution is not a good one, but how then do we make it easier for potential `helpers` contributors to figure out how to do something?

**Comment by embray** [comment]
That would be documentation. I'll work on that.

**Comment by astrofrog** [comment]
Given the move away from astropy-helpers as described in [APE 17](https://github.com/astropy/astropy-APEs/blob/master/APE17.rst), I think it's safe to close this.
