### ISSUE TITLE
Add astropy doc build to travis?

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-helpers#71]
While looking at #69, something occurred to me: a lot of the functionality here does not get tested, because it depends on getting used in some other package.  Particularly some of the docs stuff is not exhaustively unit tested because it's implicitly tested when you try to use it.

So a possible solution would be to add an astropy sphinx build to the travis build of `astropy-helpers`.  Of course that will take a lot longer, but it seems like the best way to actually test this stuff without just waiting to see if it kills astropy master.

@embray, what do you think?

**Comment by eteq** [comment]
@astrofrog - If I understand #96 right, it doesn't actually do any checks on the auto-etc sphinx machinery because the tested function doesn't have a docstring.  That's the sort of thing I meant here: checking that it actually *does* the things it's intended for with real source code.

**Comment by astrofrog** [comment]
@eteq - since #96 I have added a class which tests the automodapi stuff, but I'm not against adding a full test of the astropy build. In any case, even if not for the docs, I think we did agree during the reorganization of the ``setup_helpers`` that it would be useful to have an astropy build in the tests anyway (to ensure we don't break stuff there). Sure, it might add a bit of time to each travis build, but given how seldom we make changes to astropy-helpers, and to improve the stability, I think it would be worth it.

**Comment by embray** [comment]
I think this will be a no-go.  It would be nice to have more tests of the sphinx extensions on their own.  As it is I already test astropy-helpers against astropy before updating astropy (or any package) to use a new version of astropy-helpers, so that right there tests the astropy doc build.  Well, it tests that it succeeds.  We don't test anything about what is output.  But that would be enormously complicated compared to testing some smaller cases.
